var _tmr=_tmr||[];
(function(){function q(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function N(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Va(a,b){try{if(a.nodeName.toLowerCase()===b.toLowerCase())return a;if(a.parentNode)return Va(a.parentNode,b)}catch(c){r&&console.warn("[TopMailRu] Error#1.25",c)}return null}function Wa(a,b){if(null===a.offsetParent||(0==a.offsetHeight||0==a.offsetWidth||0==a.clientHeight||
0==a.clientWidth)||b&&(0==a.offsetLeft||0==a.offsetTop))return!1;if(void 0!==f.getComputedStyle){var c=f.getComputedStyle(a,null);return"none"!==c.display&&"hidden"!==c.visibility}return!0}function ea(a,b){for(var c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}function W(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function L(a){return"[object Array]"===Object.prototype.toString.call(a)}function R(){var a=arguments,b=a[0]||{},c=!1,d=1,e=a.length,
l,g,h,n,f;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(W(b)||(b={});d<e;d++)if(null!=(l=a[d]))for(g in l)h=b[g],n=l[g],b!==n&&(c&&n&&(W(n)||(f=L(n)))?(f?(f=!1,h=h&&L(h)?h:[]):h=h&&W(h)?h:{},b[g]=R(c,h,n)):void 0!==n&&(b[g]=n));return b}function yb(a,b,c){if(!a)return null;var d=a.match(b),e=2<arguments.length?c:0;return d&&d.length>e?d[e]:null}function Xa(a){return(""+a).replace(/[\/\^\$\*\+\?\.\|\(\)\[\]\{\}\\]/g,"\\$&")}function Ya(a){var b="";try{var c=new Uint8Array(a);f.crypto.getRandomValues(c);
for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(e){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function x(){return(new Date).getTime()}function F(a,b){var c={data:b,raw:a,url:"https://top-fwz1.mail.ru"+a},d;"function"!==typeof y.sendBeacon?d=!1:(c.dataSplitter=";",d=va(c.data,c.dataSplitter),d=!0===y.sendBeacon(c.url,d));d||(void 0===b?(c.dataSplitter=";",c.open=zb,c.connect=Ab,c.startListen=Bb,c.stopListen=Cb,c.open(c),c.connect(c)):("function"===typeof f.XMLHttpRequest?
(c.dataSplitter=";",c.open=Db,c.connect=Eb,c.startListen=Fb,c.stopListen=Gb,c.open(c),c.connect(c),d=!0):d=!1,d||Hb(c)))}function Hb(a){var b=k.createElement("iframe"),c=k.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);k.body.appendChild(c);try{var d=b.contentWindow.document,e=d.createElement("div"),l;for(l in a.data)if(a.data.hasOwnProperty(l)){var g=a.data[l],
h=typeof g;if("string"===h||"number"===h){var n=d.createElement("input");n.setAttribute("type","hidden");n.setAttribute("name",l);n.value=g;e.appendChild(n)}}var f=d.createElement("form");f.setAttribute("action",a.url);f.setAttribute("method",Za);f.setAttribute("enctype",$a);f.appendChild(e);var m=d.createElement("div");m.appendChild(f);d.body.appendChild(m);var v=function(){try{N(b,"load",v),k.body.removeChild(c)}catch(a){r&&console.warn("[TopMailRu] Error#1.2",a)}};q(b,"load",v);f.submit()}catch(p){r&&
console.warn("[TopMailRu] Error#1.3",p)}}function Db(a){a._connection=new f.XMLHttpRequest}function Eb(a){a._connection.open(Za,a.url);a._connection.setRequestHeader("Content-Type",$a);a._connection.send(va(a.data,a.dataSplitter))}function Fb(a){q(a._connection,"load",a._onload);q(a._connection,"error",a._onerror)}function Gb(a){N(a._connection,"load",a._onload);N(a._connection,"error",a._onerror)}function zb(a){a._connection=new Image}function Ab(a){a._connection.src=a.url+va(a.data,a.dataSplitter)}
function Bb(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function Cb(a){a._connection.onload=null;a._connection.onerror=null}function va(a,b){var c=b||";",d="",e;for(e in a)if(a.hasOwnProperty(e)){var l=a[e],g=typeof l;if("string"===g||"number"===g)d+=c+escape(e)+"="+escape(l)}return d}function X(a){return(a=k.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function fa(a,b,c){c=c||{};var d=c.expires;
"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var e in c)if((b=c[e])||0===b)a+="; "+e,!0!==b&&(a+="="+b);k.cookie=a}function Ca(a,b){var c=b||{};c.expires=-1;fa(a,"",c)}function Ib(){var a="tmr"+(""+Math.random()).slice(2);try{return Y=f.localStorage||null,Y.setItem(a,a),Y.removeItem(a),!0}catch(b){return Y=null,r&&console.warn("[TopMailRu] Error#1.4",b),!1}}function Da(a){try{return Y.getItem(a)}catch(b){r&&
console.warn("[TopMailRu] Error#1.5",b)}return null}function Ea(a,b){try{Y.setItem(a,b)}catch(c){r&&console.warn("[TopMailRu] Error#1.6",c)}}function Jb(){if(!Z)return null;for(var a=B.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var e=1;e<=c;e++)b=a[e]+"."+b;var e=""+x(),l={domain:b,path:"/",expires:3E5};try{fa("tmr_tcdhn",e,l);var g=X("tmr_tcdhn");Ca("tmr_tcdhn",l);if(g===e)return b}catch(h){r&&console.warn("[TopMailRu] Error#1.8",h)}}return null}function ab(a,b){Z&&fa(a,b,
Fa);S&&Ea(a,b)}function bb(a){var b=";e="+escape("detect");F(I(a,"/tracker",!1,!1)+b)}function cb(a,b){if(a.length&&null!==b.ecom_data){var c=ga(b.ecom_data),c=c?(""+c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=Ga("_m",b.ecom_method),e=Ga("_t",b.ecom_type),l=Ga("_jst",db()),c="{"+c+d+e+l+"}";F(I({id:a[0]},"/datalayer",!1,!0)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function Ga(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+
'"]'}catch(d){}return c+"false"}function Kb(){var a=X(eb);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=x()-b;return 0>b||b>fb?null:{id:a[0],version:a[1]}}function m(){}function ha(a){a&&"object"===typeof a&&(!O&&"id"in a)&&(O=a.id)}function Lb(a){return(a=!P?void 0:P[a])&&Ha?a-Ha:void 0}function gb(){if(P){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=
!P?void 0:P[b[c]];if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function ia(a){return a&&"object"===typeof a&&("id"in a&&a.id||O)}function I(a,b,c,d){S&&Ea(ja,++G);var e="id"in a?a.id:O,l="url"in a?a.url:B.href,g="referrer"in a?a.referrer:k.referrer,h="title"in a?a.title:k.title,n;n=Ia;null===n&&(n=Mb());n=null!==n?n?1:0:null;var m="userid"in a?a.userid:H||0===H?H:void 0,q=T?T:void 0,v;v=M&&a.bfCache;var p=[];O&&e!==O&&p.push("sec");"dataLayer"in f&&p.push("dl");D&&p.push(["ecom"].concat(D).join("-"));
var s=Nb();s&&s.length&&p.push(["jst"].concat(s).join("-"));v&&p.push("bfc");v=p.join(",");var t=f.screen,p=(new Date).getTimezoneOffset(),s="";if(f.Intl)try{s=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(ka){r&&console.warn("[TopMailRu] Error#1.1",ka)}s=p+"/"+s;p=hb;p=null!==p?p:Kb();a.start=gb();b=b+"?js=13"+(e?";id="+escape(e):"")+(l?";u="+escape(l):"")+(g?";r="+escape(g):"")+(a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):
"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==m?";userid="+escape(m):"")+(void 0!==q?";uparams="+escape(ga(q)):"")+(d&&h?";title="+encodeURIComponent(h):"")+(t?";s="+t.width+"*"+t.height:"")+";vp=";e=d=0;k.documentElement&&(k.documentElement.clientWidth||k.documentElement.clientHeight)?(d=k.documentElement.clientWidth,e=k.documentElement.clientHeight):"number"==typeof f.innerWidth&&(d=f.innerWidth,e=f.innerHeight);b=b+(""+d+"*"+e)+";touch="+Ob+";hds="+Pb+";frame="+Qb+";flash=";if(null===la)if(la=
"",y.plugins&&y.plugins["Shockwave Flash"])la=y.plugins["Shockwave Flash"].description.split(" ")[2];else if(f.ActiveXObject)try{var w=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),w=w.GetVariable("$version"),w=w.split(" ")[1].split(",");la=w[0]+"."+w[1]}catch(Rb){r&&console.warn("[TopMailRu] Error#1.12",Rb)}w=b+la+";sid="+ib+";ver="+jb+";tz="+encodeURIComponent(s);if(c){if(!P||!Ja)c="";else{c=[];c.push(Ja.type);c.push(Ja.redirectCount);c.push(Ha);for(b=0;b<kb.length;b++)c.push(Lb(kb[b]));c=
c.join("/")}c=";nt="+c}else c="";c=w+c+("device"in a?";device="+escape(a.device):"")+";ni=";if(!y||!y.connection)w="";else{w=y.connection;b=[];for(e=0;e<lb.length;e++){d=w[lb[e]];if(void 0!==d)switch(d){case !0:d=1;break;case !1:d=0;break;default:d=(""+d).replace(/\//g,"_")}b.push(d)}w=b.join("/")}return c+w+("params"in a?";params="+escape(ga(a.params)):"")+(null!==n?";detect="+n:"")+(Z||S?";lvid="+escape([ma,x(),G,$].join(":")):"")+(v?";opts="+escape(v):"")+(p?";flocid="+escape(p.id)+";flocv="+escape(p.version):
"")+("version"in a?";appver="+escape(a.version):"")+(aa.support?";visible="+aa.getValue():"")+";_="+Math.random()}function mb(a){a=";e="+escape("PVT/"+a);for(var b=0;b<C.length;b++)F(I(C[b],"/tracker",!1,!0)+a)}function Sb(){Ia=!0;nb(1);if(!Ka&&!na){na=!0;for(var a=0;a<C.length;a++)bb(C[a])}}function Tb(){nb(0);Ia=!1}function Mb(){var a=X(ob);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=x()-b;if(0>b||b>pb)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function nb(a){var b=
x();a=[a,b].join("|");fa(ob,a,{path:"/",expires:pb})}function Ub(){Vb||(J.pvt2=setTimeout(function(){mb(2)},2E3));Wb||(J.pvt15=setTimeout(function(){mb(15)},15E3))}function qb(){La||setInterval(function(){_tmr.beat()},6E4)}function Xb(a,b,c,d){if(!b||!d||d===Ma&&b===Ma&&c===Ma)return null;b={goal:Yb+b,value:c||0,params:{product_id:d}};a&&(b.id=a);return b}function wa(){k.addEventListener?(N(k,"DOMContentLoaded",wa),_tmr.onready()):k.attachEvent&&"complete"===k.readyState&&(N(k,"readystatechange",
wa),_tmr.onready())}function Na(a){if(M){if(a.persisted){oa=pa=xa=0;Oa=Pa=!1;a=Qa;Qa=[];for(var b=0,c=a.length;b<c;b++)_tmr.callbackOnReady(a[b]);a=ya;ya={};for(b in a)_tmr.pageView(a[b]);qb()}}else N(f,"load",Na);_tmr.onready();_tmr.onload()}function qa(){M||(N(f,"unload",qa),N(f,"beforeunload",qa));_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var f=window,y=navigator,k=document,B=location,Q="string"===typeof B.hostname?B.hostname:"",ra=-1!=Q.search(/(^|\.)odnoklassniki\.ru$/)||
-1!=Q.search(/(^|\.)ok\.ru$/),sa=-1!=Q.search(/(^|\.)vk\.com$/);Q.search(/(^|\.)mail\.ru$/);var Zb=-1!=Q.search(/(^|\.)lamoda\.ru$/),$b=-1!=Q.search(/(^|\.)kommersant\.ru$/);Q.search(/(^|\.)top\.mail\.ru$/);Q.search(/(^|\.)journal\.tinkoff\.ru$/);var ac="string"===typeof B.search&&-1!=B.search.search(/[?&]rb_clickid=/),r="string"===typeof B.search&&-1!=B.search.search(/[?&]tmr_debug=1(?:&|$)/),La=ra||sa||Zb||$b,Vb=!ac,Wb=ra||sa,bc=ra||sa,cc=ra||sa,Ka=!1,dc=!(ra||sa),M="onpageshow"in f&&"onpagehide"in
f,ga=f.JSON&&JSON.stringify?JSON.stringify.bind(JSON):function(a){return""},Za="POST",$a="application/x-www-form-urlencoded",Z=!(0===B.hostname.search(/^(\d+.)+\d+$/g)||-1!==B.hostname.search(/:/g)),Y=null,S=Ib(),Fa={domain:Jb(),path:"/",expires:287712E5};(function(){var a;if(a=k.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,e=a.length;d<e;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){d=0;for(e=a.length;d<e;d++)b=
a[d][0],Ca(b,Fa)}})();var na=!1,Ia=null,pb=864E5,ob="tmr_detect",ec=function(){function a(a,b){for(var c=a.length,g,h,f=0;f<b;f++)h=Math.floor(Math.random()*c),g=a[f],a[f]=a[h],a[h]=g;return a.slice(0,b)}function b(b,e){var l=k.createElement("div"),g=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,
50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,
101,120,116,97,100,32,116,101,120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),g=a(g,c);l.setAttribute("class",g.join(" "));l.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");l.setAttribute("id","trg-b-banners-1");l.setAttribute("data-view","SlotView.mimic");this.bait=k.body.appendChild(l);
this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=e||null;var h=this;setTimeout(function(){h._checkBait.call(h)},1)}var c=7;b.prototype._checkBait=function(){if(na)this._stop();else{var a=null!==k.body.getAttribute("abp")||!Wa(this.bait,!0);(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){r&&
console.warn("[TopMailRu] Error#1.9",c)}else if(!a&&10>this.loopNumber){var g=this;setTimeout(function(){g._checkBait.call(g)},50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(h){r&&console.warn("[TopMailRu] Error#1.10",h)}}};b.prototype._stop=function(){try{k.body.removeChild(this.bait)}catch(a){r&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),D=null,rb="ecommerce",K="dataLayer",ba=null,Ra=!1,za=[],fc=[36383,2540645,3171181,3074137,2057653],gc=[],Sa;(function(){function a(a,
b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var e={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},p=0,g=b.length;p<g;p++){var l=t[b[p]];if(l){a(e.ecom_method,[b[p]]);for(var h=0,s=l.length;h<s;h++)for(var f=0,n=d.length;f<n;f++){var k=l[h][d[f]];if(k)for(var u=0,r=c.length;u<r;u++)if(-1!==l[h].type.indexOf(c[u])){a(e.ecom_type,[c[u]]);a(e.ecom_data.events,k);break}}}}return e}function c(a,b,c){if(!a||!c||!(b in t))return null;for(var d,e=0,p=t[b].length;e<
p;e++)if(d=t[b][e],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=[],g,f,t=0,hc=a.length;t<hc;t++)if(f=a[t]){g=null;try{if(f.ecommerce)g=e(f)||l(f);else if(null===f.ecommerce)g=null;else if(f.event){var m={event:f.event,ecommerce:{}};g=e(m)||l(m)}else if("event"===f[0]){var sb=f[1],ic=f[2],A=c(sb,n,p);A&&(A.ecom_data[sb]=ic);g=A}else if(f.event===rb)a:{for(var ta=b([h],[k],[s]),E=0,u=ta.ecom_data.events.length;E<u;E++)if(!f.hasOwnProperty(ta.ecom_data.events[E])){g=
null;break a}delete ta.ecom_data.events;ta.ecom_data[rb]=f;g=ta}}catch(v){r&&console.warn("[TopMailRu] Error#1.23",v),g=null}g&&(d.push(g),za.push(g))}if(d.length){a=0;for(g=d.length;a<g;a++)cb(Aa,d[a]);D||(D=[0,0,K]);D[0]+=d.length;g=a=0;for(t=d.length;g<t;g++)a+=ga(d[g].ecom_data).length;D[1]+=a}}function e(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&(b=c(d,h,m))){if(a.event&&(d=c(a.event,h,v)))for(var e=0,g=b.ecom_type.length;e<g;e++)-1===d.ecom_type.indexOf(b.ecom_type[e])&&
(b.ecom_type.splice(e,1),g--,e--);b.ecom_data=a.ecommerce;return b}return null}function l(a){var b=a.event,d=c(b,h,v);d&&(d.ecom_data[b]=a.ecommerce);return d}function g(a){if((a=f[a])&&"function"===typeof a.push)d(a),ba=a.push,a.push=function(){var a=ba.apply(this,arguments);d([].slice.call(arguments,0));return a}}var h="push",n="gtag",k="gse",m="inner",v="outer",p="external",s="required",t={};t[n]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},
{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];t[h]=[{type:[k],
required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([n],["ga4"],[p]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},{type:["ym","gee"],inner:["add","detail","purchase","remove"]}];Sa=function(a){if(!(a===K&&ba)){a!==K&&(za=[]);var b=f[K];b&&"function"===
typeof b.push&&ba&&(b.push=ba,ba=null);g(a);Ra=!0}}})();var db=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;try{c=Object.keys(f).join(",")}catch(d){c=null}for(var e=[],l,g=0,h=a.length;g<h;g++){l=b[a[g].id];if(void 0===l)a:{l=a[g].globalVars;for(var k=c,m=0,r=l.length;m<r;m++){var v=l[m];if("string"===
typeof v&&!(v in f)||"string"===typeof v.re&&(k&&-1===k.search(RegExp("($|,)"+v.re+"(,|^)","m"))||1===r)){l=!1;break a}}l=!0}l&&(b[a[g].id]=!0,ea(a[g].id,e)||e.push(a[g].id))}return e}}(),Nb=db,fb=864E5,eb="tmr_floc",hb=null;(function(a){try{k.interestCohort&&"function"===typeof k.interestCohort&&k.interestCohort().then(function(a){hb={id:a.id,version:a.version};a=[a.id,a.version];var b=x();a=a.concat(b).join("|");fa(eb,a,{path:"/",expires:fb})},function(){})}catch(b){}})();var aa={support:!1},aa=
function(){function a(){e(g)}function b(){e(g,p)}function c(a){a.persisted&&(s[g]=null,s[h]=null,e(g,r))}function d(){return n?!k[n]:null}function e(a,b){var c=x(),e="undefined"===typeof b?d():b;if(null===s[a])s[a]={ts:c,state:e,total:0};else{var g=s[a];if(g.state!==e&&!(g.state===p&&e!==r)){var f=c-g.ts,h=g.state;g.ts=c;g.state=e;f<l||(h===r?(g.total+=f,t&&t(c,f)):h===v&&ka&&ka(c,f))}}}var l=5,g="auto",h="user",n=null,m=null,r=!0,v=!1,p=null;"hidden"in k?(n="hidden",m="visibilitychange"):"mozHidden"in
k?(n="mozHidden",m="mozvisibilitychange"):"webkitHidden"in k?(n="webkitHidden",m="webkitvisibilitychange"):"msHidden"in k&&(n="msHidden",m="msvisibilitychange");var s={};s[g]=null;var t=s[h]=null,ka=null;return{support:!!n,auto:function(d,e){t=d||null;ka=e||null;n&&(a(),q(k,m,a));M?(q(f,"pageshow",c),q(f,"pagehide",b)):(q(f,"beforeunload",b),q(f,"unload",b))},set:function(a){e(h,!!a)},getLog:function(){var a=x(),b={},c,d;for(d in s)c=s[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:d}}();
aa.auto();var tb={enabled:!1},ca=function(){function a(a,b){var c=(""+a).match(e),d={};d[g]=c;for(var f=0,l=c.length;f<l;f++)c[f]&&(d[k[f]]=c[f]);c=1<arguments.length&&void 0!==b;delete d[g];return c&&!0!==b?d[b]||null:d}function b(a,b){var d;d=(""+a).match(f)||[];var e={};e[g]=d;if(d.length){for(var h=0,k=d.length;h<k;h++)d[h]&&(e[m[h]]=d[h]);d=e}else d=null;if(!d)return null;if((e=1<arguments.length&&void 0!==b)&&(-1!==r.indexOf(b)||!0===b))for(var h=d,n=0,q=r.length;n<q;n++)(k=c(v[n]||"",h,n))&&
(h[r[n]]=k);delete d[g];return e&&!0!==b?d[b]||null:d}function c(a,b,d){var e="",g;if(W(a)&&"data"in a)e="index"in a?(b[a.data]||[])[a.index]||"":c(a.data,b,d),"re"in a&&(e=yb(e,a.re,a.reMatchIndex)||""),e&&(g=c(a.pre||"",b,d),a=c(a.post||"",b,d),e=g+e+a);else if(L(a)){g=0;for(var f=a.length;g<f;g++)e+=c(a[g],b,d)}else e=m.indexOf(a),-1===e&&(e=r.indexOf(a),e>=d&&(e=-1)),e=-1!==e?b[a]||"":""+a;return e}function d(a){var b;if(L(a)){b=[];for(var c=0,e=a.length;c<e;c++)b.push(d(a[c]));return b}b=a instanceof
RegExp?a:RegExp("^"+Xa(a)+"$");return b.test(ca.parse(B.href,"domain"))?null:b}var e=/^((mailto|tel|fax|modem)\:)(.*)$/,f=/^(?:([a-z]+):(?:([a-z]*):)?\/\/)?(?:([^:@]*)(?::([^:@]*))?@)?(?:((?:[a-z0-9_-]+\.)+[a-z]{2,}|localhost|(?:(?:[01]?\d\d?|2[0-4]\d|25[0-5])\.){3}(?:(?:[01]?\d\d?|2[0-4]\d|25[0-5]))))(?::(\d+))?(?:([^:\?\#]+))?(?:\?([^\#]+))?(?:\#([^\s]+))?$/i,g="_raw",h="hash",h="hash",k=["href","protocol","contactBy","contactTo"],m=["href","scheme","subscheme","user","pass","hostname","port","pathname",
"query",h],r=["protocol","auth","host","domain","path","search",h,"fileExtension"],v=[{data:["scheme",{pre:":",data:"subscheme"}],post:":"},[{data:"user",post:{pre:":",data:"pass"}}],[{data:g,index:5,post:{pre:":",data:"port"}}],{data:"host",re:/^(?:w{3}.)?(.*)$/,reMatchIndex:1},["pathname",{pre:"?",data:"query"}],{pre:"?",data:"query"},{pre:"#",data:h},{data:"pathname",re:/.\.([^\.]+)$/,reMatchIndex:1}];return{parse:function(c,d){return!c?null:e.test(""+c)?a(c,d):b(c,d)},getIsDomainRE:d,getDomainMask:function(a,
b,c){b=(b&&0<b?b:2)-1;var d=1;a=(""+a).replace(RegExp("^.*(?:\\.((?:[^\\.]+\\.){"+b+"}[^\\.]+$))"),"$1");if(d=a.match(/\./g))d=d.length;a="(?:^|\\.{"+(b-d+1)+"})"+Xa(a)+"$";return RegExp(c?"^((?!"+a+").)*$":a)}}}(),ub=function(){var a="checkbox color date datetime-local email file month number password radio range search tel text time url week".split(" ");return{analyze:function(b){if(!b)return null;for(var c=[].slice.apply(b.elements),d=[],e=[],f=0,g=c.length;f<g;f++){var h;a:switch(h=c[f],h.tagName.toLowerCase()){case "button":h=
!1;break a;case "input":var k=h.type.toLowerCase();if(k&&-1===a.indexOf(k)){h=!1;break a}default:h=Wa(h,!1)&&h.name&&!1===h.disabled}h&&(d.push(c[f].name),e.push(c[f].type))}return{node:b,inputsName:d.length?d:null,inputsType:e.length?e:null}},getFormByInput:function(a){if(!a)return null;a=a.form||a.getAttribute("form");return"string"===typeof a?document.getElementById(a)||null:a instanceof HTMLElement?a:null}}}(),tb=function(){function a(a){a=a||f.event;var c=(a.which||a.keyCode)===I;if("which"in
a&&a.which===D||"button"in a&&a.button&D||c){a:{a=a.target||a.srcElement;for(var c=0,d=g.length;c<d;c++){var k;b:{k=a;for(var A=g[c],p=0,E=A.types.length;p<E;p++){var u;c:{var s=k;u=A.types[p];var q=null;if(u.filter.tagName)for(var t=0,w=u.filter.tagName.length;t<w&&!(q=Va(s,u.filter.tagName[t]));t++);else q=s;if(q){if(u.filter.attr)for(s in s=void 0,u.filter.attr)if(u.filter.attr.hasOwnProperty(s)&&(t=u.filter.attr[s],w=q[s],!0===t&&!w||!1===t&&w||L(t)&&-1===t.indexOf(w))){u=null;break c}u={source:q,
type:u.type,detail:q.tagName}}else u=null}if(u){u.category=A.category;k=u;break b}}k=null}if(k){a=k;break a}}a=null}if(a){if(a.category===e){if(a.data=ca.parse(a.source.href,!0),!a.data)return}else if(a.category===l){if(a.data=ub.analyze(ub.getFormByInput(a.source)),!a.data)return}else return;c=F;if(c.enabled&&c.modes){d=0;for(k=c.modes.length;d<k;d++)if(A=a,p=c.modes[d],A.category===p.mode)if(A.category===e||A.category===l){if(p=p.categories,A.data){E=void 0;c:{E=0;for(u=p.length;E<u;E++){for(var q=
A,s=p[E],t={category:A.category},w=[],B=0,J=s.types.length;B<J;B++){var y=s.types[B],G=R({type:s.category},t),K=v in y,H;z in y?H=b(q,y,G,z):K&&(H=R({source:q.source,data:q.data,detail:y.type},G));if(H&&(!K||!b(q,y,G,v)))if(w.push(H),(y.rule&C)!==C)break}if(q=w.length?w:null){E=q;break c}}E=null}if(E){A=0;for(p=E.length;A<p;A++)c:{u=E[A];q={type:"sendEvent",category:"_"+u.category,action:u.detail};if(u.category===e&&(u.type===h||u.type===m)){if(q.label=u.data.href,!q.label)break c}else if(u.category===
x&&(q.label=u.data.node.action,!q.label))break c;_tmr.push(q)}}}}else r&&console.warn("[TopMailRu] Error#1.24","Not found tracking for type",A.type)}}}}function b(a,b,d,e){var g=!1,f=b[e];if(L(f)){var h=b[e+"Rule"]||w;e=(h&p)===p;for(var h=(h&s)===s,l=0,k=f.length;l<k&&!(g=c(a,f[l]),e&&g);l++)if(h&&!g)return null}else g=c(a,f);return!g?null:R({source:a.source,data:a.data,detail:b.type},d)}function c(a,b){var c=b.rule||w,e=(c&p)===p,c=(c&s)===s,g=!1,f;for(f in b)if(b.hasOwnProperty(f)&&"rule"!==f){var g=
b[f],h=a.data[f],g=!0===g?!!(L(h)?h.length:h):!1===g?!(L(h)?h.length:h):d(h,g);if(e&&g)break;else if(c&&!g)return!1}return g}function d(a,b){var c=a;if(c)if(L(c)){if(!c.length)return!1}else c=[c];else return!1;var d=b,e=w;if(W(d)&&!L(d)){if(!L(d.value))return!1;e=d.rule||e;d=d.value}a:{for(var g=(e&t)===t,f=(e&p)===p,e=(e&s)===s,h=!1,l=0,k=d.length;l<k;l++){var m=d[l];if(m){var q="string"===typeof m;q&&!g&&(m=m.toLowerCase());var r=m instanceof RegExp;if(q||r){var h=!0,n;b:{n=c;for(var v=g,x=0,z=
n.length;x<z;x++){var y=v?n[x]:n[x].toLowerCase();if(r&&m.test(y)||q&&m===y){n=!0;break b}}n=!1}if(f&&n){c=!0;break a}else if(e&&!n){c=!1;break a}}}}c=f?!1:e?h?!0:!1:void 0}return c}var e="click",l="submit",g=[{category:l,types:[{type:"button",filter:{tagName:["input","button"],attr:{type:["submit","image"]}}}]},{category:e,types:[{type:"a",filter:{tagName:["a"],attr:{href:!0}}}]}],h="file",m="resource",x="submit",z="filter",v="stop",p=1,s=2,t=4,C=8,w=p,F={enabled:!0,modes:[{mode:l,categories:[{category:x,
types:[{type:"lead",filter:[{inputsName:["phone"],inputsType:["tel"],rule:p},{inputsName:["email"],inputsType:["email"],rule:p}],filterRule:s,stop:{inputsName:{value:["password"]}}},{type:"form",filter:{inputsName:!0}}]}]},{mode:e,categories:[{category:"contact",types:[{type:"email",filter:{contactBy:["mailto"]}},{type:"phone",filter:{contactBy:["tel"]}}]},{category:h,types:[{type:"file",filter:{fileExtension:"7z bz2 gz apk iso cab dmg msi rar tar zip exe txt doc docx ppt pptx xls xlsx csv pdf psd rtf ods djvu eps 3gp aac ac3 avi flac flv divx midi mka mkv mp3 mp4 mpeg mpg mov ogg vob wav webm wma wmf wmv torrent".split(" ")}}]},
{category:m,types:[{type:"outgoing",rule:C,stop:{domain:[ca.getDomainMask(ca.parse(B.href,"domain"),3,!1)],href:[/password/]}},{type:"messenger",filter:{domain:ca.getIsDomainRE("vk.me t.me telegram.me telegram.im web.telegram.org m.me web.whatsapp.com api.whatsapp.com chat.whatsapp.com wa.me".split(" "))},stop:{href:[/password/]}},{type:"social",filter:{domain:ca.getIsDomainRE("vk.com vkontakte.ru m.vk.com vk.ru ok.ru m.ok.ru odnoklassniki.ru facebook.com m.facebook.com fb.com twitter.com linkedin.com instagram.com tiktok.com youtube.com youtu.be m.youtube.com".split(" "))},
stop:{href:[/password/]}}]}]}]},D=1,I=13;return{enabled:!0,start:function(){q(k,"click",a);q(k,"keypress",a)}}}();dc&&tb.start();var jb="60.3.0",xa=0,pa=0,ib=Ya(16),H=null,T=null,oa=0,ja="tmr_reqNum",G=null;Z&&(G=X(ja)||null,null!==G&&Ca(ja,Fa));S&&null===G&&(G=Da(ja)||null);G=null===G?0:parseInt(G,10);S&&Ea(ja,G);var $=(Z?X("tmr_lvid"):null)||(S?Da("tmr_lvid"):null),ma=(Z?X("tmr_lvidTS"):null)||(S?Da("tmr_lvidTS"):null);if(null===$||-1===$.search(/^[0-9a-fA-F]+$/))$=Ya(32);ab("tmr_lvid",$);if(null===
ma||-1===ma.search(/^\d+$/))ma=""+x();ab("tmr_lvidTS",ma);var O=0,C=[],Ta=[],Ba=[],Aa=[],ya={},Ob="ontouchstart"in f||1<(y.maxTouchPoints||y.msMaxTouchPoints)?"1":"0",Pb=f.devicePixelRatio||0,Qb=f.top===f?0:1,la=null,vb=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},P=vb.timing||{},Ja=vb.navigation||{},kb="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
Ha=!P?void 0:P.navigationStart,lb="downlink downlinkMax effectiveType rtt saveData type".split(" "),U,Ua;U=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||O,e=c.title||null,f,g=Ua(b,{params:c.required,fn:c.fn});if(g.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<g.missed.length&&g.missed.slice(0,-1).join(", ")+" and "||"")+g.missed.slice(-1)+" in "+a);else{var h=Ua(b,{params:c.optional,fn:c.fn});f=[].concat(g.values).concat(h.values);g=[].concat(g.missed).concat(h.missed);
c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):g.push("value"));c=f.length?"{ "+f.join(", ")+" }":"";f=g.length?"("+(1<g.length?g.slice(0,-1).join(", ")+" and "+g.slice(-1)+" are":g.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+c+" "+f):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};Ua=function(a,b){var c=[],d=[],e,f,g;if(b.params)for(e in b.params)if(b.params.hasOwnProperty(e)&&
!1!==b.params[e])if(f=e in a&&a[e],!0!==b.params[e]&&(f=f||b.params[e]),f)try{g=b.fn?b.fn:null,c.push(e+': "'+(g?g(e,f):f)+'"')}catch(h){console.warn("[TopMailRu] Error#1.16",h)}else d&&d.push(e);return{values:c,missed:d}};var J={},Qa=[];m.prototype.callbackOnReady=function(a){r&&U("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&(a.callback.call(a.context||null),M&&Qa.push(a))};m.prototype.pageView=function(a){ha(a);a:if(a&&"object"===typeof a&&a.id){5>
Ta.length&&!ea(a.id,Ta)&&(Ta.push(a.id),!1!==a.beat&&Ba.push(a.id),C.push(a),na&&bb(a));M&&(ya[a.id]=R(!0,{},a),ya[a.id].bfCache=!0);"detectBlocker"in a&&!a.detectBlocker&&(Ka=!0);var b="string"===typeof a.ecommerce,c=b&&-1!==a.ecommerce.search(/\S/);if(5>Aa.length&&!ea(a.id,Aa)&&(!0===a.ecommerce||b&&!c||b&&c||!1!==a.ecommerce&&!b&&(ea(a.id,fc)||!ea(a.id,gc)))){Aa.push(a.id);if(b&&c){if(Ra&&(Sa(a.ecommerce),K!==a.ecommerce)){K=a.ecommerce;D&&(D=[0,0,K]);break a}K=a.ecommerce;D&&(D=[0,0,K])}b=[a.id];
if(Ra)for(var c=0,d=za.length;c<d;c++)cb(b,za[c])}}r&&U("pageView",a,{title:"Page view",optional:{url:B.href}});ia(a)&&(F(I(a,"/counter",!1,!0)),pa=x())};m.prototype.reachGoal=function(a){ha(a);r&&U("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(ia(a)&&"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";F(I(a,"/tracker",!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};var Ma="VALUE";m.prototype.itemView=function(a){r&&U("itemView",a,{title:"Item view",optional:{list:!0,
pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(ia(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0,f=Xb(a.id,d,e,c);f&&this.reachGoal(f);(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||O)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();b="IV:"+e+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");F(I(a,"/tracker",!1,!0)+(";e="+escape(b)))}};var Yb=
"vk_ecom_";m.prototype.sendEvent=function(a){ha(a);r&&U("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g," ")}});if(ia(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+
c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");F(I(a,"/tracker",!1,!0)+(";e="+escape(b)))}};m.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?r&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(H=a,r&&console.info("[TopMailRu]: Global user ID = "+H))}};m.prototype.getUserID=function(){return H||0===H?H:void 0};m.prototype.deleteUserID=function(){H=null;r&&console.info("[TopMailRu]: Reset global user ID to null")};
m.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(W(a)){try{T=R(!0,{},a)}catch(b){r&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}r&&console.info("[TopMailRu]: Global user params = "+ga(T))}else r&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};m.prototype.getUserParams=function(){var a=T?T:void 0;return a?R(!0,{},a):void 0};m.prototype.deleteUserParams=function(){T=null;r&&
console.info("[TopMailRu]: Reset global user params to null")};m.prototype.getClientID=function(){var a=$;return a||0===a?a:void 0};m.prototype._MT_event=function(a,b,c){ha(a);r&&U(b,a,{title:c});ia(a)&&F(I(a,"/tracker",!1,!0)+(";e="+escape("MT:/"+b)))};m.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};m.prototype.processEvent=function(a,b){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<
b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();break;case "miniAppEvent":this.miniAppEvent(a)}}else r&&console.warn("[TopMailRu] Error#1.19",
"Unspecified type of push event");else r&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};m.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var wb=!1;m.prototype.onready=function(){wb||(wb=!0,!Ka&&!na&&ec(Sb,Tb),Sa(K))};var Pa=!1;m.prototype.onload=function(){if(!Pa){Pa=!0;oa=x();if(!bc&&0<C.length){for(var a=";e="+escape("RT/load")+";et="+oa,b=0;b<C.length;b++)F(I(C[b],"/tracker",!0,!0)+a);pa=oa}Ub()}};m.prototype.beat=function(){if(!La&&
xa){var a=x();if(!(12E4<a-xa)){if(12E4<a-pa)for(var b=";e="+escape("RT/resend")+";et="+oa,c=0;c<C.length;c++)!1!==C[c].beat&&F(I(C[c],"/tracker",!1,!0)+b);else 0<Ba.length&&F("/tracker?"+va({js:"13",id:Ba[0],e:"RT/beat",sid:ib,ids:Ba.join(),ver:jb,_:Math.random()},";"));pa=a}}};var Oa=!1;m.prototype.unload=function(){if(!Oa){Oa=!0;if(!cc){var a;a=(a=gb())?x()-a:void 0;a=";e="+escape("RT/unload")+";et="+x()+(a?";pvt="+escape(a):"");if(aa.support){var b=aa.getLog();a+=";vtauto="+b.auto}for(b=0;b<C.length;b++)F(I(C[b],
"/tracker",!1,!0)+a)}M&&(J.pvt2&&(clearTimeout(J.pvt2),delete J.pvt2),J.pvt15&&(clearTimeout(J.pvt15),delete J.pvt15),J.beat&&(clearInterval(J.beat),delete J.beat))}};m.prototype.activity=function(a){xa=x()};var da=_tmr;_tmr=new m;for(var z=0,ua=da.length,V;z<ua;z++)(V=da[z])&&"object"===typeof V&&ha(V);z=0;for(ua=da.length;z<ua;z++)V=da[z],_tmr.processEvent(V,1);z=0;for(ua=da.length;z<ua;z++)V=da[z],_tmr.processEvent(V,-1);if("complete"===k.readyState||"loading"!==k.readyState&&!k.documentElement.doScroll)_tmr.onready();
else k.addEventListener?q(k,"DOMContentLoaded",wa):k.attachEvent&&q(k,"readystatechange",wa);if("complete"===k.readyState)_tmr.onload();else M?q(f,"pageshow",Na):q(f,"load",Na);M?q(f,"pagehide",qa):(q(f,"unload",qa),q(f,"beforeunload",qa));qb();if(!La)try{for(var xb="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),jc=function(a){q(k,a,function(){_tmr.activity(a)})},z=0;z<xb.length;z++)jc(xb[z]);q(f,"scroll",function(){_tmr.activity("scallback")})}catch(kc){r&&console.warn("[TopMailRu] Error#1.20",
kc)}}})();
